server.port=8761
spring.application.name=eureka-server

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=localhost

# Actuator for health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# Logging
logging.level.root=INFO
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO


